# Generated by Django 4.0.1 on 2022-02-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressingUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jacket',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='jacket',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='jacket',
            name='quantity',
            field=models.IntegerField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='jacket',
            name='sizeEu',
            field=models.CharField(max_length=10, verbose_name='Размер (Е)'),
        ),
    ]
