# Generated by Django 4.0.1 on 2022-02-01 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DressingUp', '0002_alter_jacket_color_alter_jacket_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jacket',
            options={'ordering': ['time_create', 'name'], 'verbose_name': 'Классический Джакет', 'verbose_name_plural': 'Классические Джакеты'},
        ),
        migrations.AddField(
            model_name='jacket',
            name='photo',
            field=models.ImageField(default='images/Jackets/jacket.jpeg', upload_to='images/Jackets/%Y-%m-%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='jacket',
            name='time_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jacket',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
